package Views;

import Controllers.productoControl;
import Modells.ProductoModelo;
import java.awt.FileDialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author edd_g
 */
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Porgram
     */
    public Program() {
        initComponents();
        setResizable(false);
        setTitle("CSP: Producto Scan  V 0.0.1-alfa");
    }
    
    @Override
    public Image getIconImage()
    {
        Image retVale = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/logo.png"));
        return retVale;
    }
    public static String ruta = "";
    int count = 0;
    boolean flag_update = false;
    boolean flag_img = false;
    boolean flag = false;
    int id_aux = 0 ;
    productoControl consulta = new productoControl();
    ProductoModelo producto = new ProductoModelo();
    private byte[] getImagen(String ruta) {
        File imagen = new File(ruta);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream input = new FileInputStream(imagen);
            input.read(icono);
            return icono;
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_codigo = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_color = new javax.swing.JLabel();
        lbl_talla = new javax.swing.JLabel();
        lbl_size = new javax.swing.JLabel();
        lbl_barras = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_codigo = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        txt_talla = new javax.swing.JTextField();
        txt_size = new javax.swing.JTextField();
        txt_barras = new javax.swing.JTextField();
        lbl_imagen_ico = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_codigo_2 = new javax.swing.JLabel();
        lbl_modelos_2 = new javax.swing.JLabel();
        lbl_color_2 = new javax.swing.JLabel();
        lbl_talla_2 = new javax.swing.JLabel();
        lbl_size_2 = new javax.swing.JLabel();
        lbl_barras_2 = new javax.swing.JLabel();
        btn_modficar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txt_codigo_2 = new javax.swing.JTextField();
        txt_modelo_2 = new javax.swing.JTextField();
        txt_color_2 = new javax.swing.JTextField();
        txt_talla_2 = new javax.swing.JTextField();
        txt_size_2 = new javax.swing.JTextField();
        txt_barras_2 = new javax.swing.JTextField();
        lbl_imagen_ico_2 = new javax.swing.JLabel();
        lbl_titulo_2 = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_barras_3 = new javax.swing.JLabel();
        lbl_codigo_3 = new javax.swing.JLabel();
        lbl_modelo_3 = new javax.swing.JLabel();
        lbl_color_3 = new javax.swing.JLabel();
        lbl_tamaño_3 = new javax.swing.JLabel();
        lbl_size_3 = new javax.swing.JLabel();
        lbl_barras_4 = new javax.swing.JLabel();
        lbl_codigo_4 = new javax.swing.JLabel();
        lbl_modelo_4 = new javax.swing.JLabel();
        lbl_color_4 = new javax.swing.JLabel();
        lbl_talla_4 = new javax.swing.JLabel();
        lbl_size_4 = new javax.swing.JLabel();
        lbl_imagem_ico_3 = new javax.swing.JLabel();
        lbl_barras_5 = new javax.swing.JLabel();
        lbl_codigo_5 = new javax.swing.JLabel();
        lbl_modelo_5 = new javax.swing.JLabel();
        lbl_color_5 = new javax.swing.JLabel();
        lbl_talla_5 = new javax.swing.JLabel();
        lbl_size_5 = new javax.swing.JLabel();
        lbl_barras_6 = new javax.swing.JLabel();
        lbl_codigo_6 = new javax.swing.JLabel();
        lbl_modelo_6 = new javax.swing.JLabel();
        lbl_color_6 = new javax.swing.JLabel();
        lbl_talla_6 = new javax.swing.JLabel();
        lbl_size_6 = new javax.swing.JLabel();
        lbl_contador = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_reinicio = new javax.swing.JButton();
        btn_cambio_producto = new javax.swing.JButton();
        txt_barras_3 = new javax.swing.JTextField();
        btn_iniciar = new javax.swing.JButton();
        lbl_imagen_ico_4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lbl_url = new javax.swing.JLabel();
        lbl_port = new javax.swing.JLabel();
        lbl_DB = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_pass = new javax.swing.JLabel();
        txt_url = new javax.swing.JTextField();
        txt_port = new javax.swing.JTextField();
        txt_DB = new javax.swing.JTextField();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        btn_guardar = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_codigo.setText("Codigo:");
        jPanel1.add(lbl_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbl_modelo.setText("Modelo:");
        jPanel1.add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lbl_color.setText("Color:");
        jPanel1.add(lbl_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lbl_talla.setText("Talla:");
        jPanel1.add(lbl_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        lbl_size.setText("Size:");
        jPanel1.add(lbl_size, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        lbl_barras.setText("Codigo de Barras:");
        jPanel1.add(lbl_barras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));
        jPanel1.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));
        jPanel1.add(txt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, -1));
        jPanel1.add(txt_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));
        jPanel1.add(txt_size, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, -1));

        txt_barras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_barrasKeyTyped(evt);
            }
        });
        jPanel1.add(txt_barras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 150, -1));

        lbl_imagen_ico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_imagen_ico.setText("<html>Click para selecionar <br> una imagen");
        lbl_imagen_ico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_imagen_ico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imagen_icoMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_imagen_ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 140, 150));

        lbl_titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_titulo.setText("Registro de productos");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 35, -1, -1));

        jTabbedPane1.addTab("Registro de productos", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_codigo_2.setText("Codigo:");
        jPanel2.add(lbl_codigo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, -1));

        lbl_modelos_2.setText("Modelo:");
        jPanel2.add(lbl_modelos_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, -1));

        lbl_color_2.setText("Color:");
        jPanel2.add(lbl_color_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lbl_talla_2.setText("Talla:");
        jPanel2.add(lbl_talla_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 50, -1));

        lbl_size_2.setText("Size:");
        jPanel2.add(lbl_size_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        lbl_barras_2.setText("Codigo de Barras:");
        jPanel2.add(lbl_barras_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        btn_modficar.setText("Modificar");
        btn_modficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modficarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));
        jPanel2.add(txt_codigo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, -1));
        jPanel2.add(txt_modelo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, -1));
        jPanel2.add(txt_color_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, -1));
        jPanel2.add(txt_talla_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 160, -1));
        jPanel2.add(txt_size_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 160, -1));
        jPanel2.add(txt_barras_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 160, -1));

        lbl_imagen_ico_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_imagen_ico_2.setText("<html>Click para selecionar <br> una imagen");
        lbl_imagen_ico_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_imagen_ico_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imagen_ico_2MouseClicked(evt);
            }
        });
        jPanel2.add(lbl_imagen_ico_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 160, 160));

        lbl_titulo_2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_titulo_2.setText("Consultar | Editar | Eliminar producto");
        jPanel2.add(lbl_titulo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        lbl_buscar.setText("Buscar:");
        jPanel2.add(lbl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 169, -1));

        jTabbedPane1.addTab("Consulta de productos", jPanel2);

        lbl_barras_3.setText("<html>Codigo de<br>\n                    Brras:");

        lbl_codigo_3.setText("Codigo:");

        lbl_modelo_3.setText("Modelo:");

        lbl_color_3.setText("Color:");

        lbl_tamaño_3.setText("Talla:");

        lbl_size_3.setText("Size:");

        lbl_barras_5.setText("Codigo de Barras:");

        lbl_codigo_5.setText("Codigo:");

        lbl_modelo_5.setText("Modelo:");

        lbl_color_5.setText("Color:");

        lbl_talla_5.setText("Talla:");

        lbl_size_5.setText("Size:");

        lbl_barras_6.setText("jLabel20");

        lbl_codigo_6.setText("jLabel21");

        lbl_modelo_6.setText("jLabel22");

        lbl_color_6.setText("jLabel23");

        lbl_talla_6.setText("jLabel24");

        lbl_size_6.setText("jLabel25");

        lbl_contador.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl_contador.setText("0");

        jLabel28.setText("jLabel28");

        btn_reinicio.setText("Reiniciar contador actual");
        btn_reinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reinicioActionPerformed(evt);
            }
        });

        btn_cambio_producto.setText("Cambiar de producto");
        btn_cambio_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambio_productoActionPerformed(evt);
            }
        });

        txt_barras_3.setBackground(java.awt.Color.lightGray);
        txt_barras_3.setBorder(null);
        txt_barras_3.setCaretColor(new java.awt.Color(204, 204, 204));
        txt_barras_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_barras_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_barras_3KeyTyped(evt);
            }
        });

        btn_iniciar.setText("Seleccionar Producto");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btn_reinicio)
                                .addGap(32, 32, 32)
                                .addComponent(btn_cambio_producto)
                                .addGap(18, 18, 18)
                                .addComponent(btn_iniciar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(lbl_barras_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_barras_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_size_3)
                                                    .addComponent(lbl_tamaño_3)))
                                            .addComponent(lbl_color_3)
                                            .addComponent(lbl_modelo_3)
                                            .addComponent(lbl_codigo_3))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbl_codigo_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_modelo_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lbl_color_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lbl_talla_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbl_size_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_imagem_ico_3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txt_barras_3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_contador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_barras_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_codigo_5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_modelo_5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_color_5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_talla_5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_size_5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_codigo_6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addComponent(lbl_modelo_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_color_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_talla_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_size_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_barras_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_imagen_ico_4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel28))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_contador))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txt_barras_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_barras_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_codigo_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_modelo_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_color_5)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_talla_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_size_5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_barras_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_codigo_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_modelo_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_color_6)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_talla_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_size_6))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_imagem_ico_3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(lbl_barras_4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lbl_barras_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_codigo_3)
                                .addComponent(lbl_codigo_4))
                            .addGap(14, 14, 14)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_modelo_3)
                                .addComponent(lbl_modelo_4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_color_3)
                                .addComponent(lbl_color_4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_tamaño_3)
                                .addComponent(lbl_talla_4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_size_3)
                                .addComponent(lbl_size_4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_imagen_ico_4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reinicio)
                    .addComponent(btn_cambio_producto)
                    .addComponent(btn_iniciar))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Revision de produccion", jPanel3);

        jButton1.setText("Datos de conexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_url.setText("Servidor:");

        lbl_port.setText("Puerto:");

        lbl_DB.setText("Bae de Datos:");

        lbl_user.setText("Usuario:");

        lbl_pass.setText("Constraseña:");

        btn_guardar.setText("Modificar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Software: Producto Scan");

        jLabel2.setText("Relase: 0.0.2021_10_15-alfa");

        jLabel3.setText("Develooper: Edmundo QZ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desarrollador-de-software.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        jLabel7.setText("https://github.com/C0l3-3dd");

        jLabel8.setText("edd.go19@gmail.com");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_guardar)
                                .addGap(42, 42, 42)
                                .addComponent(btn_cancel))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_url)
                                    .addComponent(lbl_port)
                                    .addComponent(lbl_DB)
                                    .addComponent(lbl_user)
                                    .addComponent(lbl_pass))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_pass)
                                    .addComponent(txt_user, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txt_DB)
                                    .addComponent(txt_port)
                                    .addComponent(txt_url))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_url)
                            .addComponent(txt_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_port)
                            .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_DB)
                            .addComponent(txt_DB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_user)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_pass)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar)
                            .addComponent(btn_cancel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Opciones y Configuraciones", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void clean_1()
    {
        this.txt_barras.setText("");
        this.txt_codigo.setText("");
        this.txt_color.setText("");
        this.txt_modelo.setText("");
        this.txt_size.setText("");
        this.txt_talla.setText("");
        this.lbl_imagen_ico.setIcon(null);
    }

    private Icon buscarImagen()
    {
        FileDialog dialog = new FileDialog(this, "Buscar Imagen", FileDialog.LOAD);
        dialog.setVisible(true);
        ImageIcon img = new ImageIcon(dialog.getDirectory() + dialog.getFile());
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(this.lbl_imagen_ico.getWidth(), this.lbl_imagen_ico.getHeight(), Image.SCALE_DEFAULT));
        ruta = dialog.getDirectory() + dialog.getFile();
        return icon;
    }

    private ImageIcon convertirImagen(byte[] foto,int width ,int height )
    {
        ImageIcon mIcono = null;
        if (foto.length != 0) 
        {
            try 
            {
                byte[] imagen = foto;
                BufferedImage bufferedImage = null;
                InputStream inputStream = new ByteArrayInputStream(imagen);
                bufferedImage = ImageIO.read(inputStream);
                mIcono = new ImageIcon(bufferedImage.getScaledInstance(width, height, 0));
                
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error de conexión:" + e.getMessage() + "CONSULTS");
            }
        } 

        return mIcono;
    }

    private void visible5_6()
    {
        this.lbl_barras_5.setVisible(true);
        this.lbl_barras_6.setVisible(true);
        this.lbl_codigo_5.setVisible(true);
        this.lbl_codigo_6.setVisible(true);
        this.lbl_color_5.setVisible(true);
        this.lbl_color_6.setVisible(true);
        this.lbl_modelo_5.setVisible(true);
        this.lbl_modelo_6.setVisible(true);
        this.lbl_talla_5.setVisible(true);
        this.lbl_talla_6.setVisible(true);
        this.lbl_size_5.setVisible(true);
        this.lbl_size_6.setVisible(true);
        this.lbl_imagen_ico_4.setVisible(true);
    }

    private void noVisible5_6()
    {
        this.lbl_barras_5.setVisible(false);
        this.lbl_barras_6.setVisible(false);
        this.lbl_codigo_5.setVisible(false);
        this.lbl_codigo_6.setVisible(false);
        this.lbl_color_5.setVisible(false);
        this.lbl_color_6.setVisible(false);
        this.lbl_modelo_5.setVisible(false);
        this.lbl_modelo_6.setVisible(false);
        this.lbl_talla_5.setVisible(false);
        this.lbl_talla_6.setVisible(false);
        this.lbl_size_5.setVisible(false);
        this.lbl_size_6.setVisible(false);
        this.lbl_imagen_ico_4.setVisible(false);
    }
    
    private void noVisible2()
    {
        this.txt_barras_2.setEditable(false);
        this.txt_codigo_2.setEditable(false);
        this.txt_modelo_2.setEditable(false);
        this.txt_color_2.setEditable(false);
        this.txt_talla_2.setEditable(false);
        this.txt_size_2.setEditable(false);
    }
    
    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        if (this.lbl_imagen_ico.getIcon() == null) 
        {
            consulta.Insertar(this.txt_barras.getText(),
                    this.txt_codigo.getText(),
                    this.txt_modelo.getText(),
                    this.txt_color.getText(),
                    this.txt_talla.getText(),
                    this.txt_size.getText());
        } 
        else
        {
            consulta.Insertar_img(this.txt_barras.getText(),
                    this.txt_codigo.getText(),
                    this.txt_modelo.getText(),
                    this.txt_color.getText(),
                    this.txt_talla.getText(),
                    this.txt_size.getText(),
                    getImagen(ruta));
        }
        clean_1();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void lbl_imagen_icoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imagen_icoMouseClicked
        this.lbl_imagen_ico.setIcon(buscarImagen());
    }//GEN-LAST:event_lbl_imagen_icoMouseClicked

    private void txt_barrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_barrasKeyTyped
          if (this.txt_barras.getText().length() >= 13) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_barrasKeyTyped

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        clean_1();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (this.jTextField1.getText().length() >= 13) 
        {
            this.lbl_imagen_ico_2.setIcon(null);
            producto = consulta.consultar(this.jTextField1.getText());
            this.id_aux = producto.getId();
            this.txt_barras_2.setText(producto.getId_barras());
            this.txt_codigo_2.setText(producto.getCodigo());
            this.txt_color_2.setText(producto.getColor());
            this.txt_modelo_2.setText(producto.getModelo());
            this.txt_size_2.setText(producto.getSize());
            this.txt_talla_2.setText(producto.getTalla());
            this.jTextField1.setText("");
            this.lbl_imagen_ico_2.setIcon(convertirImagen(
                producto.getImagen(),
                lbl_imagen_ico_2.getWidth(),
                lbl_imagen_ico_2.getHeight()
            ));
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        ArrayList<String> data = new ArrayList<String>();
        data = consulta.precarga();
        data.add(0, "");
        Object[] items = new Object[data.size()];
        items = data.toArray();
        String item = (String) JOptionPane.showInputDialog(null, "Seleccione un articulo", "Elegir", JOptionPane.QUESTION_MESSAGE, null, items, items[0]);
        if (item != null)
        {
            producto = consulta.consultar(item);
            this.lbl_barras_4.setText(producto.getId_barras());
            this.lbl_codigo_4.setText(producto.getCodigo());
            this.lbl_color_4.setText(producto.getColor());
            this.lbl_modelo_4.setText(producto.getModelo());
            this.lbl_size_4.setText(producto.getSize());
            this.lbl_talla_4.setText(producto.getTalla());
            this.lbl_imagem_ico_3.setIcon(convertirImagen(
                producto.getImagen(),
                this.lbl_imagem_ico_3.getWidth(),
                this.lbl_imagem_ico_3.getHeight()
            ));
        }
        else
        {
            //System.exit(0);
        }
        this.txt_barras_3.setEditable(true);
        this.txt_barras_3.requestFocus();
       /* this.txt_barras_3.setBackground(this.getBackground());
        this.txt_barras_3.getCaret().setVisible(false);
        this.txt_barras_3.setCaretColor(getBackground());*/
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void txt_barras_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_barras_3KeyTyped
       try
       {
            if(!this.lbl_barras_4.getText().equals(""))
            {
                if (this.txt_barras_3.getText().length() >= 13)
                {
                    if (this.txt_barras_3.getText().equals(this.lbl_barras_4.getText())) 
                    {
                        this.count += 1;
                        this.txt_barras_3.setText("");
                        this.lbl_contador.setText(Integer.toString(count));
                        this.txt_barras_3.requestFocus();
                    }
                    else
                    {
                        try
                        {
                            visible5_6();
                            Toolkit.getDefaultToolkit().beep();
                            producto = consulta.consultar(txt_barras_3.getText());
                            this.lbl_barras_6.setText(producto.getId_barras());
                            this.lbl_codigo_6.setText(producto.getCodigo());
                            this.lbl_color_6.setText(producto.getColor());
                            this.lbl_modelo_6.setText(producto.getModelo());
                            this.lbl_size_6.setText(producto.getSize());
                            this.lbl_talla_6.setText(producto.getTalla());
                            this.lbl_imagen_ico_4.setIcon(convertirImagen(
                                                          producto.getImagen(),
                                                            140,
                                                            170));
                        }
                        catch (Exception e) 
                        {

                        }
                        JOptionPane.showMessageDialog(null, "producto incorrecto", "Error", JOptionPane.WARNING_MESSAGE);
                        noVisible5_6();
                        this.txt_barras_3.setText("");
                        this.txt_barras_3.requestFocus();
                    }
               // }
                //else if (txt_barras_3.getText().length() <= 13)
                //{
                  //  JOptionPane.showMessageDialog(null, "Formato de codigo no valido", "Error", JOptionPane.WARNING_MESSAGE);
                    //this.txt_barras_3.requestFocus();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Seleccione un producto ", "Error", JOptionPane.WARNING_MESSAGE);
                this.txt_barras_3.setText("");
            }    
        } 
        catch (Exception  e)
        {
            
        }
    }//GEN-LAST:event_txt_barras_3KeyTyped

    private void btn_reinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reinicioActionPerformed
        this.count = 0;
        this.lbl_contador.setText("0");
        this.txt_barras_3.requestFocus();
    }//GEN-LAST:event_btn_reinicioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        noVisible5_6();
        noVisible2();
        this.txt_barras_3.setEditable(false);
        this.txt_DB.setEditable(false);
        this.txt_url.setEditable(false);
        this.txt_user.setEditable(false);
        this.txt_pass.setEditable(false);
        this.txt_port.setEditable(false);
        this.btn_cancel.setEnabled(false);
        this.btn_guardar.setEnabled(false);
        this.jLabel28.setVisible(false);
        //this.txt_barras_3.setBackground(this.getBackground());
        //this.txt_barras_3.setForeground(this.btn_cambio_producto.getBackground());
                
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Images/github.png"));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(this.jLabel5.getWidth(),
                this.jLabel5.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        this.jLabel5.setIcon(iconoEscalado);
        
        ImageIcon imgIcon2 = new ImageIcon(getClass().getResource("/Images/email.png"));
        Image imgEscalada2 = imgIcon2.getImage().getScaledInstance(this.jLabel6.getWidth(),
                this.jLabel6.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado2 = new ImageIcon(imgEscalada2);
        this.jLabel6.setIcon(iconoEscalado2);
    }//GEN-LAST:event_formWindowOpened

    private void btn_modficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modficarActionPerformed
        if(flag_update == true)
        {
            int opc = JOptionPane.showOptionDialog(null, "Confirma que desea actualizar el producto", "Actualziar producto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null,new Object[] {"SI","NO"},"SI");
            if(opc == 0)
            {
                if(flag_img == true)
                {
                    consulta.update(id_aux, this.txt_barras_2.getText(), this.txt_codigo_2.getText(),this.txt_modelo_2.getText(),
                                this.txt_color_2.getText(), this.txt_talla_2.getText(), this.txt_size_2.getText(),
                                getImagen(ruta));
                    flag_img = false;
                }
                else
                {
                    producto = consulta.consultar(id_aux);
                    consulta.update(id_aux, this.txt_barras_2.getText(), this.txt_codigo_2.getText(),this.txt_modelo_2.getText(),
                                this.txt_color_2.getText(), this.txt_talla_2.getText(), this.txt_size_2.getText(),
                                producto.getImagen());
                    flag_img = false;
                    id_aux = 0 ;
                }

                this.txt_barras_2.setText("");
                this.txt_codigo_2.setText("");
                this.txt_modelo_2.setText("");
                this.txt_color_2.setText("");
                this.txt_talla_2.setText("");
                this.txt_size_2.setText("");
                this.lbl_imagen_ico_2.setIcon(null);
                noVisible2();
                this.btn_modficar.setText("Modificar");
                flag_update = false;
                this.jTextField1.setFocusable(true);
            }
            else
            {
                noVisible2();
                flag_update = false;
                this.jTextField1.setFocusable(true);
            }
            
        }
        else
        {
            if(this.txt_barras_2.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Ingrese un producto", "Error", JOptionPane.WARNING_MESSAGE);
                this.jTextField1.setFocusable(true);
            }
            else
            {
                this.txt_barras_2.setEditable(true);
                this.txt_codigo_2.setEditable(true);
                this.txt_modelo_2.setEditable(true);
                this.txt_color_2.setEditable(true);
                this.txt_talla_2.setEditable(true);
                this.txt_size_2.setEditable(true);
                this.btn_modficar.setText("Actualizar");
                flag_update = true;
                this.jTextField1.setFocusable(true);
            }   
        }  
    }//GEN-LAST:event_btn_modficarActionPerformed

    private void lbl_imagen_ico_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imagen_ico_2MouseClicked
        if(!this.txt_barras_2.getText().equals("") && flag_update == true)
        {
            this.lbl_imagen_ico_2.setIcon(buscarImagen());
            flag_img = true;
        }
        else
        {
            if(this.txt_barras_2.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Ingrese un producto", "Error", JOptionPane.WARNING_MESSAGE);
                this.jTextField1.setFocusable(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Seleciono Modificar para cambiar de imagen", "Error", JOptionPane.WARNING_MESSAGE);
                this.jTextField1.setFocusable(true);
            }
        }
    }//GEN-LAST:event_lbl_imagen_ico_2MouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if(this.txt_barras_2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Ingrese un producto", "Error", JOptionPane.WARNING_MESSAGE);
            this.jTextField1.setFocusable(true);            
        }
        else
        {
            int opc = JOptionPane.showOptionDialog(null, "Confirma que desea ELIMINAR el producto", "Eliminar producto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null,new Object[] {"SI","NO"},"SI");
            if(opc == 0)
            {
                consulta.Eliminar(id_aux);
                this.txt_barras_2.setText("");
                this.txt_codigo_2.setText("");
                this.txt_modelo_2.setText("");
                this.txt_color_2.setText("");
                this.txt_talla_2.setText("");
                this.txt_size_2.setText("");
                this.lbl_imagen_ico_2.setIcon(null);
                noVisible2();
                id_aux= 0 ;   
            }
            else
            {
                noVisible2();
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = "csp";
        String pass = "Textil_CSP";
        JPanel panel  = new JPanel();
        JLabel label = new JLabel("Ingresa la contraseña");
        JPasswordField password = new JPasswordField(10);
        panel.add(label);
        panel.add(password);
        String[] options = new String[]{"OK","CANCEL"};
        int option = JOptionPane.showOptionDialog(null, panel,"Validar",JOptionPane.NO_OPTION,JOptionPane.PLAIN_MESSAGE,null, options,options[0]);
        if(option == 0 )
        {
           char[] mander = password.getPassword();
           
           if(new String(mander).equals(pass))
           {
               this.btn_guardar.setEnabled(true);
               this.btn_cancel.setEnabled(true);
               File file = new File("./env");
               if(file.exists() == true)
               {
                   try {
                       BufferedReader bf = new BufferedReader(new FileReader(file));
                       String[] data = new String[5];
                       String temp = "";
                       int i = 0 ;
                       while((temp = bf.readLine()) != null)
                       {
                           data[i] = temp;
                           i++;
                       }
                       this.txt_url.setText(data[0]);
                       this.txt_port.setText(data[1]);
                       this.txt_DB.setText(data[2]);
                       this.txt_user.setText(data[3]);
                       this.txt_pass.setText(data[4]);
                       
                       bf.close();
                   } catch (IOException ex) {
                       Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);// cambiar ste mensaje
                   }
               }
               else
               {
                   try
                   {
                       file.createNewFile();
                       JOptionPane.showMessageDialog(null,"EL archivo de configuracion fue borrado o es la primera ves que se crea: INGRESE LOS DATOS","INGRESE LOS DATOS",JOptionPane.INFORMATION_MESSAGE);
                   }
                    catch (IOException ex)
                    {
                       Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
                    }
               }
           }
           else
           {
                JOptionPane.showMessageDialog(null, "CONTRASEÑA INCORRECTA","ERROR DE ACCESO",JOptionPane.ERROR_MESSAGE);
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try {
                if(flag_update == false)
                {
                   this.txt_DB.setEditable(true);
                   this.txt_url.setEditable(true);
                   this.txt_user.setEditable(true);
                   this.txt_pass.setEditable(true);
                   this.txt_port.setEditable(true);
                   this.btn_cancel.setEnabled(true);
                   this.btn_guardar.setText("Guardar Cambios");
                   flag_update = true;
                }
                else
                {
                    File file = new File("./env");
                    BufferedWriter wr = new BufferedWriter(new FileWriter(file));
                    PrintWriter pw = new PrintWriter(wr);
                    pw.println(this.txt_url.getText());
                    pw.println(this.txt_port.getText());
                    pw.println(this.txt_DB.getText());
                    pw.println(this.txt_user.getText());
                    pw.println(this.txt_pass.getPassword());
                    pw.close();
                    this.txt_DB.setEditable(false);
                    this.txt_url.setEditable(false);
                    this.txt_user.setEditable(false);
                    this.txt_pass.setEditable(false);
                    this.txt_port.setEditable(false);
                    this.btn_cancel.setEnabled(false);
                    this.btn_guardar.setText("Modificar");
                    flag_update = false;
                    this.txt_url.setText("");
                    this.txt_port.setText("");
                    this.txt_DB.setText("");
                    this.txt_user.setText("");
                    this.txt_pass.setText("");
                    this.btn_guardar.setEnabled(false);
                    this.btn_cancelar.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Se guardaron los datos", "Cambio de datos del servidor", JOptionPane.INFORMATION_MESSAGE);
                }           
            } catch (Exception ex) {
            }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.txt_DB.setEditable(false);
        this.txt_url.setEditable(false);
        this.txt_user.setEditable(false);
        this.txt_pass.setEditable(false);
        this.txt_port.setEditable(false);
        this.btn_cancel.setEnabled(false);
        this.btn_guardar.setText("Modificar");
        flag_update = false;
        this.txt_url.setText("");
        this.txt_port.setText("");
        this.txt_DB.setText("");
        this.txt_user.setText("");
        this.txt_pass.setText("");
        this.btn_guardar.setEnabled(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_cambio_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambio_productoActionPerformed
       noVisible5_6();
       this.lbl_barras_4.setText("");
       this.lbl_codigo_4.setText("");
       this.lbl_modelo_4.setText("");
       this.lbl_talla_4.setText("");
       this.lbl_size_4.setText("");
       this.lbl_color_4.setText("");
       this.lbl_imagem_ico_3.setIcon(null);
       this.count=0;
       this.lbl_contador.setText("0");

        ArrayList<String> data = new ArrayList<String>();
        data = consulta.precarga();
        data.add(0, "");
        Object[] items = new Object[data.size()];
        items =  data.toArray();
        String item = (String) JOptionPane.showInputDialog(null,"Seleccione un articulo","Elegir",JOptionPane.QUESTION_MESSAGE,null,items, items[0]);
        if(item != null)
        {
            producto = consulta.consultar(item);
            this.lbl_barras_4.setText(producto.getId_barras());
            this.lbl_codigo_4.setText(producto.getCodigo());
            this.lbl_color_4.setText(producto.getColor());
            this.lbl_modelo_4.setText(producto.getModelo());
            this.lbl_size_4.setText(producto.getSize());
            this.lbl_talla_4.setText(producto.getTalla());
            this.lbl_imagem_ico_3.setIcon(convertirImagen(
                producto.getImagen(),
                this.lbl_imagem_ico_3.getWidth(),
                this.lbl_imagem_ico_3.getHeight()));
        }
        else
        {
            //System.exit(0);
        }
        this.txt_barras_3.requestFocus(); 
    }//GEN-LAST:event_btn_cambio_productoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambio_producto;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_modficar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_reinicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_DB;
    private javax.swing.JLabel lbl_barras;
    private javax.swing.JLabel lbl_barras_2;
    private javax.swing.JLabel lbl_barras_3;
    private javax.swing.JLabel lbl_barras_4;
    private javax.swing.JLabel lbl_barras_5;
    private javax.swing.JLabel lbl_barras_6;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_codigo_2;
    private javax.swing.JLabel lbl_codigo_3;
    private javax.swing.JLabel lbl_codigo_4;
    private javax.swing.JLabel lbl_codigo_5;
    private javax.swing.JLabel lbl_codigo_6;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_color_2;
    private javax.swing.JLabel lbl_color_3;
    private javax.swing.JLabel lbl_color_4;
    private javax.swing.JLabel lbl_color_5;
    private javax.swing.JLabel lbl_color_6;
    private javax.swing.JLabel lbl_contador;
    private javax.swing.JLabel lbl_imagem_ico_3;
    private javax.swing.JLabel lbl_imagen_ico;
    private javax.swing.JLabel lbl_imagen_ico_2;
    private javax.swing.JLabel lbl_imagen_ico_4;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_modelo_3;
    private javax.swing.JLabel lbl_modelo_4;
    private javax.swing.JLabel lbl_modelo_5;
    private javax.swing.JLabel lbl_modelo_6;
    private javax.swing.JLabel lbl_modelos_2;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_port;
    private javax.swing.JLabel lbl_size;
    private javax.swing.JLabel lbl_size_2;
    private javax.swing.JLabel lbl_size_3;
    private javax.swing.JLabel lbl_size_4;
    private javax.swing.JLabel lbl_size_5;
    private javax.swing.JLabel lbl_size_6;
    private javax.swing.JLabel lbl_talla;
    private javax.swing.JLabel lbl_talla_2;
    private javax.swing.JLabel lbl_talla_4;
    private javax.swing.JLabel lbl_talla_5;
    private javax.swing.JLabel lbl_talla_6;
    private javax.swing.JLabel lbl_tamaño_3;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo_2;
    private javax.swing.JLabel lbl_url;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField txt_DB;
    private javax.swing.JTextField txt_barras;
    private javax.swing.JTextField txt_barras_2;
    private javax.swing.JTextField txt_barras_3;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigo_2;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_color_2;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_modelo_2;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_size;
    private javax.swing.JTextField txt_size_2;
    private javax.swing.JTextField txt_talla;
    private javax.swing.JTextField txt_talla_2;
    private javax.swing.JTextField txt_url;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}